### ISSUE TITLE
'WSGIRequest' object has no attribute 'REQUEST'

### ISSUE THREAD

**Issue by Haikson** [smacker/django-filebrowser-no-grappelli#18]
```
'WSGIRequest' object has no attribute 'REQUEST'
/local/lib/python2.7/site-packages/filebrowser/sites.py in browse, line 355
```

```
Environment:

Request Method: GET

Django Version: 1.9
Python Version: 2.7.6
Installed Applications:
('mptt',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'datetimewidget',
 'virtenviro',
 'virtenviro.content',
 'virtenviro.news',
 'virtenviro.shop',
 'virtenviro.registration',
 'filebrowser')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware')



Traceback:

File "/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/local/lib/python2.7/site-packages/filebrowser/decorators.py" in decorator
  45.         return function(request, *args, **kwargs)

File "/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/local/lib/python2.7/site-packages/django/views/decorators/clickjacking.py" in wrapped_view
  39.         resp = view_func(*args, **kwargs)

File "/local/lib/python2.7/site-packages/filebrowser/sites.py" in browse
  355.             'is_popup': "pop" in request.REQUEST,   # ChangeList uses "pop"

Exception Type: AttributeError at /filebrowser/browse/
Exception Value: 'WSGIRequest' object has no attribute 'REQUEST'
```

**Comment by smacker** [comment]
Yes. It doesn't work with django 1.9 right now. Will be fixed soon.

**Comment by jbreuer95** [comment]
ETA available?

**Comment by rkakrik** [comment]
Same problem(

**Comment by smacker** [comment]
I fixed it. I'll show some warnings, but everything should works okay.
Please, if you use Django 1.9, test it and let me know if you have any issues.

**Comment by lucacorti** [comment]
Works for me on Django 1.9.

**Comment by smacker** [comment]
Good! Thanks. I close the issue then.
